### PR TITLE
Refactor drawutils

### PR DESCRIPTION
**Pull request by Gjum**
I want to put in an abstraction layer to make porting the code to different GUI toolkits a lot easier.

This makes it possible to use the same code for different graphical frontends.

### CODE REVIEW

**Comment by metalmatze** [comment]
Looks good to me.
But what is the `c` variable that's everywhere. Maybe you could rename it, to `canvas`, `cell` or whatever it is?!

**Comment by Gjum** [comment]
It was the cairo context, now it is an instance of `Canvas`.

Yeah, it should probably renamed, I was just too lazy to type canvas each time.

And I'm also not sure if canvas is a good name for the wrapper.

**Comment by Gjum** [comment]
Merging for now. Renaming will happen later maybe.

**Comment by metalmatze** [comment]
> maybe

**Comment by Gjum** [comment]
Yeah, well, I have seen others understand the code as it is.

**Pull request merged**
