### PR TITLE
Ui changes

### PR DESCRIPTION
**Pull request by xzfc**

### CODE REVIEW

**Comment by Gjum** [comment]
I have started to merge your changes, see the `ui` branch.

**Comment by xzfc** [comment]
Maybe replace cairo text rendering with pango due to the reasons mentioned in [1](http://cairographics.org/FAQ/#using_pango)? Tldr:  `cairo_show_text` draws ▯ if symbol is not presented in main font face; pango uses different font in that case.

**Comment by Gjum** [comment]
As I said, this client started as a sandbox and I didn't expect it to become my most popular project.

Pango would be cool, but honestly I want to focus on other stuff. If you have time to do this. I'd really appreciate it.

**Comment by Gjum** [comment]
I will merge the `ui` branch as it is in a few hours. Please comment if there is anything left to talk about.

**Comment by Gjum** [comment]
I left the leaderboard right-aligned for now, because I like it that way. But I understand the issue and you are not the only one preferring a different look. I opened #7 for that, so I won't forget it.

**Pull request merged**
